// src/views/Init.vue
<template>
  <div class="page-container">
    <h1>系统初始化</h1>
    <UiCard>
      <div class="init-section">
        <h3>数据库操作</h3>
        <p class="text-muted">更新数据库表结构</p>
        <UiButton @click="updateTables" :loading="loading.updateTables">
          更新表结构
        </UiButton>
      </div>

      <div class="init-section">
        <h3>初始化数据</h3>
        <p class="text-muted">创建默认角色和权限</p>
        <div class="form-row">
          <UiInput v-model="adminUsername" placeholder="管理员用户名" />
          <UiInput v-model="adminPassword" type="password" placeholder="管理员密码" />
        </div>
        <UiButton @click="initData" :loading="loading.initData">
          初始化数据
        </UiButton>
      </div>

      <div class="init-section danger">
        <h3>危险操作</h3>
        <p class="text-error">删除所有数据表，此操作不可恢复！</p>
        <UiButton variant="danger" @click="dropTables" :loading="loading.dropTables">
          删除所有表
        </UiButton>
      </div>

      <UiAlert v-if="message" :type="messageType">{{ message }}</UiAlert>
    </UiCard>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { UiCard, UiButton, UiInput, UiAlert } from '@/components/ui'
import { initApi } from '@/services/authService'

const adminUsername = ref('')
const adminPassword = ref('')
const message = ref('')
const messageType = ref<'success' | 'error' | 'info'>('info')

const loading = ref({
  updateTables: false,
  initData: false,
  dropTables: false
})

const updateTables = async () => {
  loading.value.updateTables = true
  message.value = ''
  try {
    const { data } = await initApi.updateTables()
    message.value = data.message
    messageType.value = 'success'
  } catch (err: any) {
    message.value = err.response?.data?.detail || '更新失败'
    messageType.value = 'error'
  } finally {
    loading.value.updateTables = false
  }
}

const initData = async () => {
  loading.value.initData = true
  message.value = ''
  try {
    const { data } = await initApi.initData(adminUsername.value || undefined, adminPassword.value || undefined)
    message.value = data.message || '数据初始化成功'
    messageType.value = 'success'
  } catch (err: any) {
    message.value = err.response?.data?.detail || '初始化失败'
    messageType.value = 'error'
  } finally {
    loading.value.initData = false
  }
}

const dropTables = async () => {
  if (!confirm('确定要删除所有数据表吗？此操作不可恢复！')) return
  loading.value.dropTables = true
  message.value = ''
  try {
    const { data } = await initApi.dropTables()
    message.value = data.message
    messageType.value = 'success'
  } catch (err: any) {
    message.value = err.response?.data?.detail || '删除失败'
    messageType.value = 'error'
  } finally {
    loading.value.dropTables = false
  }
}
</script>

// src/pages/Init.tsx
import { useState } from 'react';
import { initApi } from '../api';
import { Button, Card, Input, Alert } from '../components/ui';

function Init() {
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [adminUsername, setAdminUsername] = useState('admin');
  const [adminPassword, setAdminPassword] = useState('admin123');

  const handleInit = async (action: 'update' | 'data' | 'all' | 'drop') => {
    setLoading(true);
    setMessage('');
    setError('');
    try {
      let res;
      switch (action) {
        case 'update':
          res = await initApi.updateTables();
          setMessage(res.data.message);
          break;
        case 'data':
          res = await initApi.initData(adminUsername, adminPassword);
          setMessage(res.data.message + (res.data.admin_exists ? '' : `, 管理员: ${res.data.admin_username}`));
          break;
        case 'all':
          res = await initApi.initAll(adminUsername, adminPassword);
          setMessage(res.data.message + (res.data.admin_exists ? '' : `, 管理员: ${res.data.admin_username}`));
          break;
        case 'drop':
          res = await initApi.dropTables();
          setMessage(res.data.message);
          break;
      }
    } catch (err: any) {
      setError(err.response?.data?.detail || '操作失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page-content">
      <div className="page-header">
        <h1>系统初始化</h1>
      </div>

      {message && (
        <Alert variant="success" onClose={() => setMessage('')}>
          {message}
        </Alert>
      )}
      {error && (
        <Alert variant="error" onClose={() => setError('')}>
          {error}
        </Alert>
      )}

      <Card title="初始化设置">
        <div className="form-row">
          <Input
            label="管理员用户名"
            value={adminUsername}
            onChange={setAdminUsername}
            placeholder="默认: admin"
          />
          <Input
            label="管理员密码"
            type="password"
            value={adminPassword}
            onChange={setAdminPassword}
            placeholder="默认: admin123"
          />
        </div>

        <div className="flex gap-md" style={{ marginTop: '24px', flexWrap: 'wrap' }}>
          <Button
            variant="primary"
            onClick={() => handleInit('all')}
            disabled={loading}
          >
            {loading ? '处理中...' : '完整初始化'}
          </Button>
          <Button
            variant="secondary"
            onClick={() => handleInit('update')}
            disabled={loading}
          >
            更新表结构
          </Button>
          <Button
            variant="secondary"
            onClick={() => handleInit('data')}
            disabled={loading}
          >
            初始化数据
          </Button>
          <Button
            variant="danger"
            onClick={() => handleInit('drop')}
            disabled={loading}
          >
            删除所有表
          </Button>
        </div>
      </Card>

      <Card title="说明">
        <ul style={{ paddingLeft: '20px', lineHeight: '1.8', color: '#45515e' }}>
          <li><strong>完整初始化：</strong>更新所有表结构并初始化数据（角色、权限、管理员用户）</li>
          <li><strong>更新表结构：</strong>执行所有DDL语句，创建新表或新增缺失的列（幂等操作，可重复执行）</li>
          <li><strong>初始化数据：</strong>创建默认角色、权限和管理员用户（已存在则跳过）</li>
          <li><strong>删除所有表：</strong>删除所有数据库表（数据将丢失）</li>
        </ul>
        <p style={{ marginTop: '16px', color: '#8e8e93', fontSize: '14px' }}>
          默认管理员账号：admin / admin123
        </p>
      </Card>
    </div>
  );
}

export default Init;
